apiVersion: v1
kind: Ingress
metadata:
  name: inception_service
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: inception_service
          servicePort: 8000